version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_DB
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sirius
      POSTGRES_USER: sirius_user
      POSTGRES_PASSWORD: sirius_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
